### ISSUE TITLE
sql-words in other languages

### ISSUE THREAD

**Issue by ostinelli** [capnrefsmmat/seuss#5]
Hi, thank you for this!
I'd like to be able to use seuss for different languages, in particular I'd like to generate Italian poems.

Where did you get the `words.sql.gz` dictionary, so I can see if there's a version of it in another language?

**Comment by capnrefsmmat** [comment]
I believe I used [this project](http://rhyme.sourceforge.net/), which automatically builds a rhyming dictionary by using a pronouncing dictionary of English. I converted its data to SQL form instead of using GDBM.

If you find a pronouncing dictionary in your own language, you could probably use a similar method to make a rhyming dictionary out of it.

**Comment by ostinelli** [comment]
Thank you for your response. Ouch, I have not been able to find a downloadable rhyme dictionary, it probably will be as hard to find a pronouncing one :) Will see.
